#과거에 사용하던 방식
#KAKAO API - QR
#secret-key: ${ed1df4b9d47e4cb603d7dbc8e7124cbb}
#cid: TC0ONETIME
#approval-url: http://localhost:8080/cart/payment/qr/success
#cancel-url:   http://localhost:8080/cart/payment/qr/cancel
#fail-url:     http://localhost:8080/cart/payment/qr/fail


# src/main/resources/application.yml - 해당 경로에 .yml 확장자로 파일을 생성 해야 한다.
#현재 사용하는 방식
kakao:
  pay:
    host: https://kapi.kakao.com
    admin-key: 910b33c043e132455291bf76c041da78 # 실제 발급받은 본인의 키를 기입!!
    cid: TC0ONETIME                 # 가맹점 코드 (테스트용), 개발자가 코드를 직접 작성하면 안됨!!❌
    ready-path: /payment/ready      # 카카오페이 호출 주소, 개발자가 코드를 직접 작성하면 안됨!!❌
    approve-path: /payment/approve  # 카카오페이 인증 주소, 개발자가 코드를 직접 작성하면 안됨!!❌